version: '3.1'
services:
  postgres:
    build: ./postgres
    restart: always
    logging:
      options:
        max-size: 10m
        max-file: "3"
      ports:
        - '5432:5432'
      volumes_from:
        - db-data

  db-data:  
    image: cogniteev/echo
    command: echo 'Data Container for PostgreSQL'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  tomcat:  
  build: ./tomcat
  ports:
    - "8081:8080"
  links:
    - postgres
